import Link from 'next/link';

/**
 * /admin/finance/[id]/edit — DEPRECATED.
 *
 * Editing invoices in-place is deprecated. Invoices generated by the new
 * Phase D flow are immutable Stripe Checkout Sessions — they cannot be
 * edited after creation. To change an invoice:
 *
 *   - If unpaid: void the existing invoice and re-generate
 *   - If paid: issue a refund and re-generate
 *
 * Both flows live on the invoice detail page (or /admin/invoice-drafts/[id]
 * for Phase D drafts). This edit form is preserved as a no-op page so any
 * stale links don't 500.
 */
export default async function DeprecatedEditInvoicePage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  return (
    <div className="mx-auto max-w-2xl p-8">
      <div className="rounded-lg border border-amber-300 bg-amber-50 p-6">
        <div className="flex items-start gap-3">
          <svg
            className="mt-0.5 h-6 w-6 flex-shrink-0 text-amber-600"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2}
            aria-hidden="true"
          >
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01M5 19h14a2 2 0 001.84-2.75L13.74 4a2 2 0 00-3.48 0L3.16 16.25A2 2 0 005 19z" />
          </svg>
          <div className="flex-1">
            <h1 className="text-lg font-semibold text-amber-900">
              Invoice editing is deprecated
            </h1>
            <p className="mt-2 text-sm text-amber-900">
              Invoices integrate with Stripe and can&rsquo;t be edited after creation.
              To make changes:
            </p>
            <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-amber-900">
              <li>If <strong>unpaid</strong>: void the invoice and re-generate from the job</li>
              <li>If <strong>paid</strong>: issue a refund and re-generate</li>
            </ul>

            <div className="mt-5 flex gap-3">
              <Link
                href={`/admin/finance/${id}`}
                className="inline-flex items-center gap-2 rounded-md bg-stone-900 px-4 py-2 text-sm font-medium text-white hover:bg-stone-800"
              >
                View invoice
              </Link>
              <Link
                href="/admin/finance"
                className="inline-flex items-center rounded-md border border-stone-300 bg-white px-4 py-2 text-sm font-medium text-stone-700 hover:bg-stone-50"
              >
                Back to Finance
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
